global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['110.15.58.113:9999']

  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['110.15.58.113:7777']

  - job_name: 'node'
    static_configs:
      - targets: ['110.15.58.113:9100']
