# ./prometheus.yml

global:
  scrape_interval: 30s  # 기본 스크랩 간격을 30초로 설정

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m  # 이 잡의 스크랩 간격을 1분으로 설정
    static_configs:
      - targets: ['110.15.58.113:9999']

  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 1m  # 디스커버리 정보 갱신 간격을 1분으로 설정
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['110.15.58.113:7777']
    scrape_interval: 1m  # 이 잡의 스크랩 간격을 1분으로 설정

  - job_name: 'node'
    static_configs:
      - targets: ['110.15.58.113:9100']
    scrape_interval: 1m  # 이 잡의 스크랩 간격을 1분으로 설정

  - job_name: 'jenkins_job'
    metrics_path: '/prometheus'
    scheme: 'http'
    static_configs:
      - targets: ['110.15.58.113:8082']