# ./prometheus.yml

global:
  scrape_interval: 15s  # 기본 스크랩 간격을 15초로 설정

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['110.15.58.113:9999']  # Prometheus 자체 메트릭을 수집

  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock  # Docker 소켓을 통해 Docker 서비스 디스커버리 설정
        refresh_interval: 30s  # 디스커버리 정보 갱신 간격을 30초로 설정
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name  # 컨테이너 이름을 레이블로 설정

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['110.15.58.113:7777']  # cAdvisor 메트릭을 수집

  - job_name: 'node'
    static_configs:
      - targets: ['110.15.58.113:9100']  # Node Exporter 메트릭을 수집
