# /home/ubuntu/Project/BootGenie/grafana/provisioning/datasources/datasource.yml

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://110.15.58.113:9999
    isDefault: true
